#!/bin/bash
set -e

JITSI_HOST="___JITSI_HOST___"

rm -f /etc/nginx/sites-enabled/$JITSI_HOST.conf
rm -f /etc/nginx/sites-enabled/$JITSI_HOST-dev.conf

ln -s ../sites-available/$JITSI_HOST.conf /etc/nginx/sites-enabled/

systemctl restart nginx
