#!/bin/bash

# -----------------------------------------------------------------------------
# JIBRI-EPHEMERAL-CONFIG
# -----------------------------------------------------------------------------
#
# Customize the Jibri config for the current instance
#
# -----------------------------------------------------------------------------
INSTANCE=$(hostname)
[[ "$INSTANCE" = "eb-jibri-template" ]] && exit 0

(( INSTANCE_ID = $(hostname | egrep -o '[0-9]+$') + 0 ))
LOOPBACK=$(aplay -l | grep "card $INSTANCE_ID:" | grep -i loopback | \
           cut -d ' ' -f3 | uniq)


[ -n "$INSTANCE" ] && \
    sed -i "s/\(.*\"nickname\":\).*/\1 \"$INSTANCE-$RANDOM\"/" \
        /etc/jitsi/jibri/config.json
[ -n "$LOOPBACK" ] && \
    sed -i "s/Loopback,/$LOOPBACK,/" /home/jibri/.asoundrc
