#!/bin/bash
set -e

# -----------------------------------------------------------------------------
# ADD-JIBRI-NODE
# -----------------------------------------------------------------------------
# Add an additional Jibri node to the cluster.
#
# Usage:
#     add-jibri-node <NODE-ADDRESS>
# -----------------------------------------------------------------------------
NODE=$1
SSH_CONFIG=/root/.ssh/jms-config
INSTALLER=https://raw.githubusercontent.com/emrahcom/emrah-buster-base/master/installer/eb
INSTALLER_CONFIG=https://raw.githubusercontent.com/emrahcom/emrah-buster-templates/master/installer/eb-jibri.conf
JITSI_ROOTFS=/var/lib/lxc/eb-jitsi/rootfs
JIBRI_ROOTFS=/var/lib/lxc/eb-jibri-template/rootfs
DEFAULT_ROUTE=$(ip route | egrep '^default ' | head -n1)
PUBLIC_INTERFACE=${DEFAULT_ROUTE##*dev }
PUBLIC_INTERFACE=${PUBLIC_INTERFACE/% */}
REMOTE_IP=$(ip addr show $PUBLIC_INTERFACE | ack "$PUBLIC_INTERFACE$" | \
            xargs | cut -d " " -f 2 | cut -d "/" -f1)

ssh_() {
    ssh -F $SSH_CONFIG $NODE -- "$@"
}

scp_() {
    scp -F $SSH_CONFIG $1 $NODE:$2
}


# -----------------------------------------------------------------------------
# trap on exit
# -----------------------------------------------------------------------------
function on_exit {
    if [[ "$COMPLETED" != true ]]; then
        cat <<EOF

Something went wrong. The installation couldn't be completed!
EOF
        exit 1
    else
        cat <<EOF

Completed successfully!
EOF
        exit 0
    fi
}

COMPLETED=false
trap on_exit EXIT

[[ -z "$NODE" ]] && cat <<EOF
Usage:
       add-jibri-node <NODE-ADDRESS>
EOF


# -----------------------------------------------------------------------------
# check
# -----------------------------------------------------------------------------
KERNEL=$(ssh_ uname -r)
ARCH=$(ssh_ dpkg --print-architecture)

ssh_ "modprobe snd_aloop 2>/dev/null || true"
if [ -z "$(ssh_ grep snd_aloop /proc/modules)" ]; then
    cat <<EOF

The node's kernel ($KERNEL) does not support snd_aloop module.

Please install the standard Linux kernel package to the node and reboot it.
Probably it's "linux-image-$ARCH" for your case.

EOF

exit 1
fi


# -----------------------------------------------------------------------------
# cluster related parameters
# -----------------------------------------------------------------------------
if [[ -f $JIBRI_ROOTFS/etc/jitsi/jibri/jibri.conf ]]; then
    JITSI_HOST=$(egrep '\s*xmpp-domain\s*=' \
                     $JIBRI_ROOTFS/etc/jitsi/jibri/jibri.conf | \
                 cut -d'"' -f2 | xargs)
    PASSWD1=$(sed -n '/\s*control-login\s*{/,/}/p' \
                     $JIBRI_ROOTFS/etc/jitsi/jibri/jibri.conf | \
              egrep '\s*password\s*=' | cut -d'"' -f2 | xargs)
    PASSWD2=$(sed -n '/\s*call-login\s*{/,/}/p' \
                     $JIBRI_ROOTFS/etc/jitsi/jibri/jibri.conf | \
              egrep '\s*password\s*=' | cut -d'"' -f2 | xargs)
else
    JITSI_HOST=$(egrep -v '//.*' $JIBRI_ROOTFS/etc/jitsi/jibri/config.json | \
              jq '.xmpp_environments[0].xmpp_domain' | xargs)
    PASSWD1=$(egrep -v '//.*' $JIBRI_ROOTFS/etc/jitsi/jibri/config.json | \
              jq '.xmpp_environments[0].control_login.password' | xargs)
    PASSWD2=$(egrep -v '//.*' $JIBRI_ROOTFS/etc/jitsi/jibri/config.json | \
              jq '.xmpp_environments[0].call_login.password' | xargs)
fi


# -----------------------------------------------------------------------------
# installation
# -----------------------------------------------------------------------------
ssh_ apt-get -y --allow-releaseinfo-change update
ssh_ apt-get -y install wget
ssh_ wget $INSTALLER -O /tmp/eb
ssh_ wget $INSTALLER_CONFIG -O /tmp/eb-jibri.conf

ssh_ "echo export JITSI_HOST=$JITSI_HOST >>/tmp/eb-jibri.conf"
ssh_ "cd /tmp && bash eb eb-jibri"


# -----------------------------------------------------------------------------
# configuration
# -----------------------------------------------------------------------------
[[ -n "$(ssh_ dig +short $JITSI_HOST)" ]] || \
    ssh_ "echo \"$REMOTE_IP\t$JITSI_HOST\" >> $JIBRI_ROOTFS/etc/hosts"

scp_ $JITSI_ROOTFS/usr/local/share/ca-certificates/jms-CA.crt \
    $JIBRI_ROOTFS/usr/local/share/ca-certificates/
ssh_ sed -i \"s/___JITSI_HOST___/$JITSI_HOST/\" \
    $JIBRI_ROOTFS/etc/jitsi/jibri/jibri.conf
ssh_ sed -i \"s/___PASSWD1___/$PASSWD1/\" \
    $JIBRI_ROOTFS/etc/jitsi/jibri/jibri.conf
ssh_ sed -i \"s/___PASSWD2___/$PASSWD2/\" \
    $JIBRI_ROOTFS/etc/jitsi/jibri/jibri.conf

ssh_ lxc-start -n eb-jibri-template
ssh_ lxc-wait -n eb-jibri-template -s RUNNING

ssh_ "lxc-attach -n eb-jibri-template -- update-ca-certificates"
ssh_ "lxc-attach -n eb-jibri-template -- zsh -c \" \
    set -e
    certutil -A -n 'jitsi' -i /usr/local/share/ca-certificates/jms-CA.crt \
        -t 'TCu,Cu,Tu' -d sql:/home/jibri/.pki/nssdb/
    chown jibri:jibri /home/jibri/.pki -R\""

ssh_ lxc-stop -n eb-jibri-template
ssh_ lxc-wait -n eb-jibri-template -s STOPPED
ssh_ systemctl start jibri-ephemeral-container.service


# -----------------------------------------------------------------------------
# completed
# -----------------------------------------------------------------------------
COMPLETED=true
