#!/bin/bash
set -e

# -----------------------------------------------------------------------------
# SET-LETSENCRYPT-CERT
# -----------------------------------------------------------------------------
# Get and set the Let's Encrypt certificate for the Jitsi container
#
# Usage:
#     set-letsencrypt-cert <FQDN>
# -----------------------------------------------------------------------------
FQDN=$1

[[ -z "$FQDN" ]] && cat <<EOF

Usage:
    set-letsencrypt-cert <FQDN>
EOF

lxc-attach -n eb-jitsi -- /usr/local/sbin/set-letsencrypt-cert $FQDN
